{% set name = "MetObs-toolkit" %}
{% set version = "1.0.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/metobs_toolkit-{{ version }}.tar.gz
  sha256: 98c04e41577432fdd95fb57c2a573a0ef41b0e03aba4b78ae19114d6325c0456

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - cartopy >=0.23
    - earthengine-api <=1.6.11
    - geemap >=0.35.3
    - geopandas >=1.0.1
    - mapclassify >=2.8.1
    - matplotlib-base >=3.9.2
    - numpy >=1
    - pandas >=2
    - pint >=0.24.4
    - setuptools >=78.1.0
    - shapely >=2.0.6
    - xarray >=2022.3.0
    - pyarrow >=21.0.0
    - netcdf4 >=1.7.2

test:
  imports:
    - metobs_toolkit
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: "https://metobs-toolkit.readthedocs.io/en/latest/"
  summary: A Meteorological observations toolkit for scientists
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - vergauwenthomas
    - pratiman-91
